#!/bin/sh

if [ -f /etc/postfix/Makefile ]; then
    echo "### postfix: /usr/bin/make -f /etc/postfix/Makefile"
    /usr/bin/make -f /etc/postfix/Makefile
fi

echo "### postfix: /etc/init.d/postfix restart"
/etc/init.d/postfix restart

